[profile.default]
  auto_detect_solc = false
  optimizer = true
  optimizer_runs = 200
  out = "out"
  solc = "0.8.29"
  src = "src"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
